import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=['Config','Core','News','Metrics'].map(name=>fs.readFileSync('dist/'+name+'.gs','utf8')).join('\n');
function context(email='felix.delbarrio@bbva.com'){
 const c=vm.createContext({console}),properties={OWNER_EMAIL:'felix.delbarrio@bbva.com',SPREADSHEET_ID:'book'},cache=new Map();
 c.PropertiesService={getScriptProperties:()=>({getProperty:k=>properties[k]||null,setProperty:(k,v)=>properties[k]=v})};
 c.Session={getActiveUser:()=>({getEmail:()=>email}),getEffectiveUser:()=>({getEmail:()=> 'felix.delbarrio@bbva.com'})};
 c.CacheService={getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})};
 c.LockService={getScriptLock:()=>({tryLock:()=>true,waitLock(){},releaseLock(){}})};
 vm.runInContext(source,c);return c;
}
const feed={name:'BBVA',domain:'bbva.com',entity:'BBVA',country:'Sin determinar'},now=new Date('2026-10-09T12:00:00Z'),item={title:'BBVA financia a empresas',excerpt:'Operación de financiación corporativa',url:'https://www.bbva.com/es/noticia/?utm_source=rss',date:'2026-10-08T11:00:00Z'};
test('fecha, dominio y ventana son obligatorios; no inventa impacto',()=>{const c=context();const r=c.evaluate_(item,feed,now);assert.equal(r.item.topic,'Financiación');assert.equal(r.item.url,'https://www.bbva.com/es/noticia/');for(const change of [{date:''},{url:'https://bbva.com.evil.net/a'},{date:'2026-10-10'},{date:'2026-09-01'}])assert.ok(c.evaluate_({...item,...change},feed,now).reason);assert.equal(r.item.impacto,undefined);});
test('excluye ruido retail; admite incidencias de banca empresarial',()=>{const c=context();assert.equal(c.classify_('Cómo ahorrar en vacaciones',''),'');assert.equal(c.classify_('Sostenibilidad en casa',''),'');assert.equal(c.classify_('Incidencia en BBVA Net Cash para empresas',''),'Continuidad de servicio');});
test('canonicalización, limpieza y protección contra fórmulas',()=>{const c=context();assert.equal(c.canonicalUrl_('https://BBVA.com/a?z=1&utm_source=x&id=2#x'),'https://bbva.com/a?id=2&z=1');assert.equal(c.canonicalUrl_('javascript:alert(1)'),'');assert.equal(c.canonicalUrl_('https://user:pass@bbva.com/a'),'');assert.equal(c.domainMatches_('https://evilbbva.com/a','bbva.com'),false);assert.equal(c.safeCell_('=IMPORTXML("x")'),'\'=IMPORTXML("x")');assert.equal(c.plainText_('<script>x()</script><p>BBVA &amp; empresas &#243;</p>'),'BBVA & empresas ó');});
test('dominio y administrador se comprueban con identidad activa, nunca con propietario efectivo',()=>{for(const email of ['reader@bbva.com','felix.delbarrio@bbva.com'])assert.doesNotThrow(()=>context(email).authorize_());for(const email of ['','reader@evilbbva.com','reader@bbva.com.evil'])assert.throws(()=>context(email).authorize_());const reader=context('reader@bbva.com');assert.equal(reader.authorize_().admin,false);for(const name of ['getAudit','getAdoption','getTelemetry','getCandidates','startSearch','retrySearchErrors','setupRadar'])assert.throws(()=>reader[name](),/no autorizado/);assert.throws(()=>reader.verifyNews({}),/no autorizado/);assert.throws(()=>reader.saveFeeds([]),/no autorizado/);});
test('dashboard de lector no entrega hojas, configuración ni datos de otros usuarios',()=>{const c=context('reader@bbva.com');c.rows_=(name)=>name==='Noticias'?[]:[{inicio:'2026-10-09'}];c.feeds_=()=>[feed];c.book_=()=>{throw Error('No debe obtener URL de hoja');};const d=c.getDashboard({});for(const key of ['sheetUrl','runs','feeds','scoreRules','search','searchCountries','email'])assert.equal(key in d,false);assert.equal(d.admin,false);assert.equal(d.sourceCount,1);});
test('todas las reglas estratégicas generan signo y tipo coherentes, con evidencia requerida',()=>{const c=context(),rules=vm.runInContext('SCORE_RULES',c);for(const r of rules){const result=c.score_(r.id,'CIB','Evidencia literal explícita del hecho y del rol del banco.');assert.equal(result.impacto,r.score);assert.equal(result.tipo_impacto,r.score>0?'Oportunidad':r.score<0?'Amenaza':'Neutral');}assert.throws(()=>c.score_('unknown','CIB','evidence'));assert.throws(()=>c.score_('neutral','retail','Evidencia literal explícita con suficiente longitud.'));assert.throws(()=>c.score_('neutral','CIB','breve'));});
test('resumen estratégico solo usa hechos verificados y mantiene cinco frases',()=>{const c=context(),rows=[{estado:'Pendiente de revisión',tema:'Financiación',pais:'España',impacto:5},{estado:'Verificada',tema:'Financiación',pais:'México',impacto:-3}];const insights=c.insights_(rows);assert.equal(insights.length,5);assert.match(insights[3],/1 amenazas y 0 oportunidades/);assert.ok(insights.every(s=>s.split(/\s+/).length<=40));});
test('todos los alias, competidores y temas del JSON están en el plan; no inventa URLs editoriales',()=>{const c=context();let written;const sheet={getLastRow:()=>1};c.book_=()=>({getSheetByName:()=>sheet});c.rows_=()=>[];c.Utilities={getUuid:()=> 'cycle'};c.append_=(name,rows)=>{if(name==='Busquedas')written=rows;};c.ScriptApp={getProjectTriggers:()=>[],newTrigger:()=>({timeBased(){return this;},everyMinutes(){return this;},create(){}})};c.startSearch_();const profile=JSON.parse(fs.readFileSync('assets/news-profile.json'));for(const geo of profile.geographies){for(const competitor of geo.competitors)assert.ok(written.some(r=>r[1]===geo.name&&r[3]===competitor));for(const alias of profile.primary.aliases)assert.ok(written.some(r=>r[1]===geo.name&&r[3]===alias));for(const topic of profile.topics)assert.ok(written.some(r=>r[1]===geo.name&&r[4]===topic));}assert.equal(written.filter(r=>r[3]==='BBVA').length,105);assert.match(c.searchQuery_({pais:'España',idioma:'es',entidad:'BBVA Empresas',tema:'incidencia',iteracion:0}),/incidencia/);assert.match(c.searchUrl_({pais:'México',idioma:'es',entidad:'Banorte Empresas',tema:'Competidores locales',iteracion:0}),/^https:\/\/news.google.com\/rss\/search\?/);});
test('adopción identifica usuarios en servidor y métricas separan períodos y sesiones',()=>{const c=context(),events=[{fecha:'2026-10-09T10:00:00Z',correo:'a@bbva.com',sesion:'1',evento:'vista',vista:'radar'},{fecha:'2026-10-07T10:00:00Z',correo:'a@bbva.com',sesion:'2',evento:'rendimiento',duracion_ms:'100'},{fecha:'2026-09-15T10:00:00Z',correo:'b@bbva.com',sesion:'3',evento:'error'},{fecha:'2026-08-01T10:00:00Z',correo:'c@bbva.com',sesion:'4',evento:'vista'}];const m=c.metrics_(events,now.getTime());assert.equal(m.dau,1);assert.equal(m.wau,1);assert.equal(m.mau,2);assert.equal(m.returning,1);assert.equal(m.sessions,3);assert.equal(m.latencyP95,100);assert.equal(m.failures,1);let saved;c.append_=(name,rows)=>saved=rows;c.trim_=()=>{};c.pruneEvents_=()=>{};c.recordEvents([{session:'test-session-123456',event:'acceso',view:'radar',email:'forged@bbva.com'}]);assert.equal(saved[0][1],'felix.delbarrio@bbva.com');assert.throws(()=>context('reader@bbva.com').recordEvents([{session:'test-session-123456',event:'vista',view:'adoption'}]),/restringida/);});
test('verificación rechaza cita inexistente y fecha que no confirma el editor',()=>{const c=context();c.feeds_=()=>[];c.UrlFetchApp={fetch:()=>({getResponseCode:()=>200,getContentText:()=>'<h1>BBVA financia empresas en España</h1><script type="application/ld+json">{"datePublished":"2026-10-08"}</script><p>BBVA lidera una financiación para empresas de España.</p>'})};const input={criterion:'neutral',line:'CIB',url:'https://bbva.com/a',evidence:'Cita inventada que nunca ha aparecido en la noticia original.',title:'BBVA financia empresas en España',entity:'BBVA',country:'España',date:'2026-10-08'};assert.throws(()=>c.verifyNews(input),/literalmente/);assert.equal(c.articleDate_('<meta content="2026-10-08T10:00:00Z" property="article:published_time">'),'2026-10-08');assert.equal(c.articleDate_('{"datePublished":"2026-10-08"}'),'2026-10-08');});
test('recopilación conserva errores parciales y deduplica sin fusionar operaciones',()=>{const c=context(),saved={};let released=false;c.LockService={getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>released=true})};c.Utilities={getUuid:()=> 'id',formatDate:d=>d.toISOString().slice(0,10)};c.UrlFetchApp={fetch:url=>{if(url==='bad')throw Error('503');return {getResponseCode:()=>200,getContentText:()=>'<rss/>'};}};c.feeds_=()=>[{...feed,url:'good'},{...feed,url:'bad'}];c.knownUrls_=()=>new Set();c.parseFeed_=()=>[{...item,date:new Date(Date.now()-86400000).toISOString()},{...item,date:new Date(Date.now()-86400000).toISOString()}];c.append_=(name,rows)=>saved[name]=rows;c.telemetry_=()=>{};const r=c.collect_();assert.equal(r.added,1);assert.equal(r.errors.length,1);assert.equal(saved.Noticias[0].length,16);assert.equal(saved.Noticias[0][11],'');assert.equal(saved.Ejecuciones[0][3],'Parcial');assert.equal(released,true);});
test('distribución modular, cliente válido y activos autónomos',()=>{assert.equal(fs.existsSync('src/Code.gs'),false);for(const file of ['Config','Core','News','Metrics'])assert.ok(fs.existsSync('dist/'+file+'.gs'));new vm.Script(fs.readFileSync('src/Client.html','utf8').replace(/^<script>\s*|\s*<\/script>\s*$/g,''));assert.ok(!fs.readFileSync('assets/bia.svg','utf8').includes('fill="white"'));assert.ok(fs.readFileSync('dist/Index.html','utf8').includes('font/woff2;base64'));assert.match(fs.readFileSync('src/Index.html','utf8'),/data-admin hidden data-view="adoption"/);const manifest=JSON.parse(fs.readFileSync('src/appsscript.json'));assert.equal(manifest.oauthScopes.length,4);assert.ok(!manifest.oauthScopes.some(x=>/gmail|drive|admin.directory/.test(x)));});
test('búsqueda publica candidatos, conserva errores y no asigna país ni impacto',()=>{const c=context(),saved={},changes=[];c.Utilities={getUuid:()=> 'candidate',formatDate:d=>d.toISOString().slice(0,10)};const date=new Date(Date.now()-86400000).toISOString();c.rows_=name=>name==='Busquedas'?[{ciclo:'cycle',pais:'España',idioma:'es',entidad:'BBVA',tema:'Financiación',iteracion:'0',sin_nuevos:'0',estado:'Pendiente'},{ciclo:'cycle',pais:'México',idioma:'es',entidad:'BBVA',tema:'DCM',iteracion:'0',sin_nuevos:'0',estado:'Pendiente'}]:[];c.book_=()=>({getSheetByName:()=>({getLastRow:()=>1,getRange:(row)=>({setNumberFormat(){return this;},setValues(values){changes.push([row,values]);return this;}})})});let fetched=0;c.UrlFetchApp={fetch:()=>++fetched===1?{getResponseCode:()=>200,getContentText:()=>'<rss/>'}:{getResponseCode:()=>503}};c.parseFeed_=()=>[{title:'BBVA empresas',url:'https://news.google.com/rss/articles/123',date,source:'Editor'}];c.append_=(name,rows)=>saved[name]=rows;c.telemetry_=()=>{};c.searchTick_();assert.equal(saved.Candidatos.length,1);assert.equal(saved.Candidatos[0][7],'Pendiente');assert.equal(saved.Candidatos[0][6],'');assert.equal(saved.Noticias,undefined);assert.equal(changes[1][1][0][2],'Reintento programado');assert.equal(changes[1][1][0][0],0);assert.ok(saved.Auditoria.some(r=>r[5].includes('HTTP 503')));});

test('verificación reconoce países en su idioma y recuperación escribe un solo lote',()=>{const c=context();assert.equal(c.countryMention_('Garanti BBVA Türkiye için finansman sağlıyor.','Turquía'),true);assert.equal(c.countryMention_('BBVA United Kingdom loan.','Reino Unido'),true);assert.equal(c.countryMention_('préstamo únicamente en México','España'),false);let writes=0,saved;c.rows_=()=>[{estado:'Error',fecha:'2026-10-09',resultados:'0',error:'[3] HTTP 503'},{estado:'Índice agotado',fecha:'2026-10-08',resultados:'3',error:''}];c.book_=()=>({getSheetByName:()=>({getRange:()=>({setNumberFormat(){return this;},setValues(rows){writes++;saved=rows;}})})});c.ScriptApp={getProjectTriggers:()=>[{getHandlerFunction:()=> 'searchTick_'}]};assert.match(c.retrySearchErrors(),/^1 líneas/);assert.equal(writes,1);assert.equal(saved[0][0],'Pendiente');assert.equal(saved[1][0],'Índice agotado');});

test('verifica noticias de hoy antes del mediodía y rechaza fechas futuras',()=>{const c=context(),saved={};const fixed='2026-10-09T09:00:00Z';c.Date=class extends Date{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return new Date(fixed).getTime();}};c.Utilities={getUuid:()=> 'verified',formatDate:d=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(d)};const evidence='BBVA lidera una financiación empresarial en España mediante un préstamo de 150 millones de euros.';c.feeds_=()=>[];c.rows_=()=>[];c.append_=(name,rows)=>saved[name]=rows;c.UrlFetchApp={fetch:()=>({getResponseCode:()=>200,getContentText:()=>'<h1>BBVA financia empresas en España</h1><script type="application/ld+json">{"datePublished":"2026-10-09"}</script><p>'+evidence+'</p>'})};const input={criterion:'liderazgo',line:'CIB',url:'https://bbva.com/a',evidence,title:'BBVA financia empresas en España',entity:'BBVA',country:'España',date:'2026-10-09'};assert.match(c.verifyNews(input),/puntuación 5/);assert.equal(saved.Noticias[0][11],5);assert.equal(saved.Noticias[0][9],'Verificada');assert.throws(()=>c.verifyNews({...input,date:'2026-10-10'}),/ventana/);});
