import {$,escape,message} from '../core/dom.js';
import {call} from '../core/api.js';
import {downloadNewsletter} from './briefing.js';
const fieldLabels={type:'Tipo de entidad',entity:'Entidad',segment:'Segmento',country:'Ámbito',topic:'Tema',signal:'Novedad',source:'Fuente'};
const periods={monthly:'Mensual',weekly:'Semanal',daily:'Diaria'};
export function createSubscriptions({run,onApply}){
  let options,own=[],all=[];
  const filterFields=(catalogs,filter,selected)=>Object.entries(catalogs).map(([key,values])=>`<label>${fieldLabels[key]}<select name="${key}"><option value="">Todos</option>${values.map(value=>`<option${selected(value,filter[key])}>${escape(value)}</option>`).join('')}</select></label>`).join('');
  const editorId=admin=>admin?'admin-subscription-editor':'personal-editor';
  function edit(admin,row){
    const defaults=options.defaults,filter=row?.filtros||defaults.filters,id=editorId(admin),selected=(a,b)=>a===b?' selected':'';
    $(id).innerHTML=`<form data-subscription-form data-admin="${admin}" data-id="${escape(row?.id||'')}"><p class="eyebrow">${row?'EDITAR SUSCRIPCIÓN':'DISEÑA TU NEWSLETTER'}</p><h2>${row?'Ajusta tu seguimiento.':'Solo lo que te aporta valor.'}</h2><p class="muted">${admin?'Alta y gestión para el dominio BBVA.':escape(options.email)}</p>${admin?`<label>Correo corporativo<input name="email" type="email" required value="${escape(row?.correo||'')}" placeholder="nombre@bbva.com"></label>`:''}<label>Nombre<input name="name" required maxlength="100" value="${escape(row?.nombre||defaults.name)}"></label><label>Periodicidad<select name="periodicity">${Object.entries(periods).map(([value,label])=>`<option value="${value}"${selected(value,row?.periodicidad||defaults.periodicity)}>${label}</option>`).join('')}</select></label><div class="subscription-fields">${filterFields(Object.fromEntries(Object.entries(options.catalogs).filter(([key])=>['entity','segment','country'].includes(key))),filter,selected)}</div><details class="subscription-more"><summary>Personalizar contenido <span class="muted">Tipo, tema, novedad y fuente</span></summary><div class="subscription-fields">${filterFields(Object.fromEntries(Object.entries(options.catalogs).filter(([key])=>!['entity','segment','country'].includes(key))),filter,selected)}</div><label>Palabras clave<input name="search" maxlength="160" value="${escape(filter.search||'')}" placeholder="Opcional"></label></details><label class="subscription-active"><input name="active" type="checkbox"${row?.activa===false?'':' checked'}> Suscripción activa</label><p class="small muted">Recibirás las novedades del período completo anterior. Si no hay novedades, no enviamos un correo vacío.</p><button class="button primary" type="submit">${row?'Guardar cambios':admin?'Crear suscripción':'Suscribirme'}</button></form>`;
  }
  function cards(rows,admin){return rows.map(row=>`<article class="panel selection-card"><div class="news-meta"><span class="badge">${periods[row.periodicidad]}</span><span class="badge">${row.activa?'Activa':'Pausada'}</span></div><h3>${escape(row.nombre)}</h3>${admin?`<p>${escape(row.correo)}</p><p class="small muted">${escape(row.ultimaEntrega?row.ultimaEntrega.estado+' · '+row.ultimaEntrega.desde+' / '+row.ultimaEntrega.hasta:'Sin entregas registradas')}</p>`:''}<p class="muted">${escape(Object.values(row.filtros).filter(Boolean).join(' · ')||'Todo el sector')} · ${row.filtros.country?'':'Todos los ámbitos · '}Novedades del canal</p><div class="actions"><button class="button primary" data-action="edit" data-id="${escape(row.id)}">Editar</button>${admin?'':`<button class="button" data-action="export" data-id="${escape(row.id)}">Vista previa ↗</button><button class="button" data-action="apply" data-id="${escape(row.id)}">Explorar</button><button class="button" data-action="delete" data-id="${escape(row.id)}">Dar de baja</button>`}</div></article>`).join('')||'<div class="panel empty"><h3>Tu próxima novedad empieza aquí.</h3><p>Crea una suscripción con el foco que necesita tu equipo.</p></div>';}
  async function open(admin=false){
    const [settings,rows]=await Promise.all([call('getNewsletterOptions'),call(admin?'getAdminSubscriptions':'getSubscriptions')]);options=settings;
    if(admin){all=rows;$('subscribers-count').textContent=new Set(rows.map(r=>r.correo)).size+' suscriptores · '+rows.length+' suscripciones';$('admin-subscriptions-list').innerHTML=cards(rows,true);}
    else{own=rows;$('subscriptions-list').innerHTML=cards(rows,false);$('newsletter-delivery-status').textContent=options.enabled?'Entrega periódica activa. Recibirás únicamente las novedades de tu selección.':'Puedes guardar tu suscripción. El administrador todavía debe activar la entrega.';}
    edit(admin);if(!admin)$('newsletter-default-period').textContent=periods[options.defaults.periodicity]+' por defecto';
  }
  for(const admin of [false,true]){
    const target=$(editorId(admin));
    target.addEventListener('submit',event=>{event.preventDefault();const form=event.target,data=new FormData(form),filters={};for(const key of [...Object.keys(options.catalogs),'search'])filters[key]=String(data.get(key)||'');run(async()=>{message(await call(admin?'saveAdminSubscription':'saveSubscription',{id:form.dataset.id||undefined,email:data.get('email'),name:data.get('name'),periodicity:data.get('periodicity'),active:data.has('active'),filters}));await open(admin);},false);});
    $(admin?'new-admin-subscription':'new-subscription').addEventListener('click',()=>edit(admin));
    $(admin?'admin-subscriptions-list':'subscriptions-list').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const row=(admin?all:own).find(r=>r.id===button.dataset.id);if(!row)return;if(button.dataset.action==='edit')edit(admin,row);if(button.dataset.action==='apply')onApply(row.query);if(button.dataset.action==='export')run(async()=>downloadNewsletter(await call('exportNewsletter',{subscriptionId:row.id})),false);if(button.dataset.action==='delete')run(async()=>{message(await call('deleteSubscription',row.id));await open();},false);});
  }
  return {open};
}
